"""Deterministic, self-contained HTML reporting for product artifacts."""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any
from uuid import uuid4

from .product_core import validate_product_artifact


REPORT_TEXT = {
    "zh_CN": {
        "html_lang": "zh-CN",
        "title": "BIMChange-Agent 分析报告",
        "subtitle": "受限 IFC4 预览 · 确定性差分为权威数据源 · AI 仅用于可选解释",
        "previous": "旧版本",
        "revised": "新版本",
        "summary": "变更摘要",
        "supported": "受支持变更",
        "added": "新增",
        "deleted": "删除",
        "modified": "属性修改",
        "unsupported": "未支持",
        "details": "变更明细",
        "type": "类型",
        "entity": "实体",
        "storey": "楼层",
        "field": "字段",
        "old": "旧值",
        "new": "新值",
        "empty": "没有检测到受支持的变更",
        "unsupported_title": "未支持的检测结果",
        "unsupported_note": "这些 IfcDiff 标志被保留，但没有被包装成受支持的 Change Record。",
        "reason": "原因",
        "selector": "证据选择器",
        "ai_title": "AI 解读",
        "ai_disabled": "本次分析未启用 AI。确定性 IFC 差分报告仍然完整可用。",
        "generated": "由 {provider} · {model} 生成",
        "natural_summary": "自然语言摘要",
        "rational": "简短理性分析",
        "key_changes": "重点变更",
        "limitations": "证据限制",
        "no_key_changes": "没有可列出的重点变更。",
        "no_limitations": "模型未补充其他限制；仍须遵守以下免责声明。",
        "rational_unavailable": "AI 解读未成功生成，无法形成基于模型输出的理性分析。",
        "boundary": "边界与警告",
        "disclaimer": "免责声明：AI 内容仅用于辅助阅读；确定性 Change Records 与原始证据才是权威数据源。本报告不能替代专业 BIM 协调、工程审查或结构安全评估。",
    },
    "en": {
        "html_lang": "en",
        "title": "BIMChange-Agent analysis report",
        "subtitle": "Bounded IFC4 preview · deterministic diff is authoritative · AI is optional explanation only",
        "previous": "Previous version",
        "revised": "Revised version",
        "summary": "Change summary",
        "supported": "Supported changes",
        "added": "Added",
        "deleted": "Deleted",
        "modified": "Property changes",
        "unsupported": "Unsupported",
        "details": "Change details",
        "type": "Type",
        "entity": "Entity",
        "storey": "Storey",
        "field": "Field",
        "old": "Previous value",
        "new": "Revised value",
        "empty": "No supported changes were detected",
        "unsupported_title": "Unsupported detections",
        "unsupported_note": "These IfcDiff flags are retained but are not presented as supported Change Records.",
        "reason": "Reason",
        "selector": "Evidence selector",
        "ai_title": "AI explanation",
        "ai_disabled": "AI was not enabled. The deterministic IFC diff remains fully available.",
        "generated": "Generated by {provider} · {model}",
        "natural_summary": "Natural-language summary",
        "rational": "Brief rational analysis",
        "key_changes": "Key changes",
        "limitations": "Evidence limitations",
        "no_key_changes": "No key changes were provided.",
        "no_limitations": "No additional limitation was supplied; the disclaimer below still applies.",
        "rational_unavailable": "The AI explanation was not generated, so no model-based rational analysis is available.",
        "boundary": "Boundaries and warnings",
        "disclaimer": "Disclaimer: AI content is reading assistance only. Deterministic Change Records and source evidence remain authoritative. This report does not replace professional BIM coordination, engineering review, or structural safety assessment.",
    },
}


def _label(language: str, key: str) -> str:
    return REPORT_TEXT.get(language, REPORT_TEXT["zh_CN"])[key]


def _text(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, (dict, list, bool, int, float)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value)


def _escape(value: Any) -> str:
    return html.escape(_text(value), quote=True)


def _change_rows(artifact: dict[str, Any], language: str) -> str:
    rows: list[str] = []
    for change in artifact["changes"]:
        storey = change["location"]["building_storey"]
        field = change["field"]
        field_text = (
            f"{field['property_set']}.{field['name']}" if field is not None else "—"
        )
        rows.append(
            "<tr>"
            f"<td><span class='badge'>{_escape(change['change_type'])}</span></td>"
            f"<td>{_escape(change['entity_type'])}</td>"
            f"<td><code>{_escape(change['global_id'])}</code></td>"
            f"<td>{_escape(storey['name'] if storey else None)}</td>"
            f"<td>{_escape(field_text)}</td>"
            f"<td>{_escape(change['old_value'])}</td>"
            f"<td>{_escape(change['new_value'])}</td>"
            "</tr>"
        )
    if not rows:
        return f"<tr><td colspan='7' class='empty'>{_label(language, 'empty')}</td></tr>"
    return "".join(rows)


def _warning_items(artifact: dict[str, Any]) -> str:
    return "".join(f"<li>{_escape(item)}</li>" for item in artifact["warnings"])


def _unsupported_rows(artifact: dict[str, Any]) -> str:
    return "".join(
        "<tr>"
        f"<td><code>{_escape(item['global_id'])}</code></td>"
        f"<td>{_escape(item['reason'])}</td>"
        f"<td><code>{_escape(item['selector'])}</code></td>"
        "</tr>"
        for item in artifact["unsupported_changes"]
    )


def _ai_section(explanation: dict[str, Any] | None, language: str) -> str:
    if explanation is None:
        return f"<p class='muted'>{_label(language, 'ai_disabled')}</p>"
    provider = explanation.get("provider", "deepseek")
    model = explanation.get("model", "unknown")
    content = explanation.get("explanation", explanation)
    if not isinstance(content, dict):
        content = {}

    def prose(value: Any) -> str:
        return f"<p>{_escape(value)}</p>"

    def bullets(field: str, empty_key: str) -> str:
        values = content.get(field, [])
        if not isinstance(values, list):
            values = []
        entries = "".join(
            f"<li>{_escape(value)}</li>"
            for value in values
            if isinstance(value, str) and value.strip()
        )
        return f"<ul>{entries}</ul>" if entries else prose(_label(language, empty_key))

    rational = content.get("rational_analysis")
    if not isinstance(rational, str) or not rational.strip():
        rational = _label(language, "rational_unavailable")
    generated = _label(language, "generated").format(
        provider=_escape(provider), model=_escape(model)
    )
    return (
        f"<p class='muted'>{generated}</p>"
        f"<h3>{_label(language, 'natural_summary')}</h3>{prose(content.get('summary'))}"
        f"<h3>{_label(language, 'rational')}</h3>{prose(rational)}"
        f"<h3>{_label(language, 'key_changes')}</h3>{bullets('key_changes', 'no_key_changes')}"
        f"<h3>{_label(language, 'limitations')}</h3>{bullets('limitations', 'no_limitations')}"
    )


def build_html_report(
    artifact: dict[str, Any],
    *,
    explanation: dict[str, Any] | None = None,
    language: str = "zh_CN",
) -> str:
    """Build one deterministic, offline-viewable HTML report."""
    validate_product_artifact(artifact)
    summary = artifact["summary"]
    unsupported_section = ""
    if artifact["unsupported_changes"]:
        unsupported_section = f"""
        <section>
          <h2>{_label(language, 'unsupported_title')}</h2>
          <p class="muted">{_label(language, 'unsupported_note')}</p>
          <div class="table-wrap"><table>
            <thead><tr><th>GlobalId</th><th>{_label(language, 'reason')}</th><th>{_label(language, 'selector')}</th></tr></thead>
            <tbody>{_unsupported_rows(artifact)}</tbody>
          </table></div>
        </section>
        """
    return f"""<!doctype html>
<html lang="{_label(language, 'html_lang')}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{_label(language, 'title')}</title>
  <style>
    :root {{ color-scheme: light; --ink:#202327; --muted:#6D7175; --line:#D4D2CC; --panel:#F6F4EF; --accent:#8E4E36; --canvas:#F2F1ED; }}
    * {{ box-sizing:border-box; }}
    body {{ margin:0; color:var(--ink); background:var(--canvas); font:14px/1.6 "Segoe UI Variable Text", "Segoe UI", "Microsoft YaHei UI", sans-serif; }}
    main {{ width:min(1280px, calc(100% - 40px)); margin:28px auto; }}
    header, section {{ background:#FBFAF7; border:1px solid var(--line); border-radius:12px; padding:24px; margin-bottom:16px; }}
    h1 {{ margin:0 0 8px; font-size:28px; }} h2 {{ margin:0 0 14px; font-size:19px; }}
    .muted {{ color:var(--muted); }}
    .files {{ display:grid; grid-template-columns:1fr 1fr; gap:12px; margin-top:18px; }}
    .file {{ background:var(--panel); border-radius:10px; padding:13px 15px; }}
    .cards {{ display:grid; grid-template-columns:repeat(5, minmax(120px,1fr)); gap:10px; }}
    .card {{ border:1px solid var(--line); border-radius:11px; padding:15px; }}
    .card strong {{ display:block; font-size:24px; color:var(--accent); }}
    .table-wrap {{ overflow:auto; }} table {{ width:100%; border-collapse:collapse; }}
    th, td {{ padding:10px 11px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; }}
    th {{ background:var(--panel); position:sticky; top:0; }} code {{ font-size:12px; }}
    .badge {{ display:inline-block; background:#e7eff2; color:#244c5d; border-radius:999px; padding:2px 8px; }}
    .empty {{ text-align:center; color:var(--muted); padding:28px; }}
    h3 {{ margin:18px 0 6px; font-size:15px; }}
    footer {{ color:var(--muted); text-align:center; padding:12px; }}
    @media (max-width:800px) {{ .files, .cards {{ grid-template-columns:1fr; }} main {{ width:calc(100% - 20px); }} }}
  </style>
</head>
<body><main>
  <header>
    <h1>{_label(language, 'title')}</h1>
    <p class="muted">{_label(language, 'subtitle')}</p>
    <div class="files">
      <div class="file"><strong>{_label(language, 'previous')}</strong><br>{_escape(artifact['source']['file_name'])}<br><code>{_escape(artifact['source']['sha256'])}</code></div>
      <div class="file"><strong>{_label(language, 'revised')}</strong><br>{_escape(artifact['revised']['file_name'])}<br><code>{_escape(artifact['revised']['sha256'])}</code></div>
    </div>
  </header>
  <section>
    <h2>{_label(language, 'summary')}</h2>
    <div class="cards">
      <div class="card">{_label(language, 'supported')}<strong>{summary['total_supported']}</strong></div>
      <div class="card">{_label(language, 'added')}<strong>{summary['added']}</strong></div>
      <div class="card">{_label(language, 'deleted')}<strong>{summary['deleted']}</strong></div>
      <div class="card">{_label(language, 'modified')}<strong>{summary['property_modified']}</strong></div>
      <div class="card">{_label(language, 'unsupported')}<strong>{summary['unsupported']}</strong></div>
    </div>
  </section>
  <section>
    <h2>{_label(language, 'details')}</h2>
    <div class="table-wrap"><table>
      <thead><tr><th>{_label(language, 'type')}</th><th>{_label(language, 'entity')}</th><th>GlobalId</th><th>{_label(language, 'storey')}</th><th>{_label(language, 'field')}</th><th>{_label(language, 'old')}</th><th>{_label(language, 'new')}</th></tr></thead>
      <tbody>{_change_rows(artifact, language)}</tbody>
    </table></div>
  </section>
  {unsupported_section}
  <section><h2>{_label(language, 'ai_title')}</h2>{_ai_section(explanation, language)}</section>
  <section><h2>{_label(language, 'boundary')}</h2><ul>{_warning_items(artifact)}</ul></section>
  <footer>{_label(language, 'disclaimer')}</footer>
</main></body></html>"""


def write_html_report(
    artifact: dict[str, Any],
    output_path: Path,
    *,
    explanation: dict[str, Any] | None = None,
    language: str = "zh_CN",
) -> Path:
    """Write a self-contained UTF-8 HTML report and return its absolute path."""
    output_path = output_path.expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_name(f".{output_path.name}.{uuid4().hex}.tmp")
    try:
        temporary.write_text(
            build_html_report(
                artifact, explanation=explanation, language=language
            ),
            encoding="utf-8",
        )
        temporary.replace(output_path)
    finally:
        try:
            temporary.unlink(missing_ok=True)
        except OSError:
            pass
    return output_path
